version: '3.8'

services:
  attendance_middleware:
    build: .
    container_name: attendance_middleware
    restart: always
    ports:
      - "8999:8999"
    volumes:
      # Mount the data folder to persist the SQLite database and internal files
      - ./data:/app/data
    environment:
      # Set timezone to GMT+7
      - TZ=Asia/Jakarta 
