"""initial_schema

Revision ID: 4c757a619595
Revises: 
Create Date: 2026-05-19 09:46:37.118724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c757a619595'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_id'), 'admin_users', ['id'], unique=False)
    op.create_index(op.f('ix_admin_users_username'), 'admin_users', ['username'], unique=True)
    op.create_table('adms_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adms_credentials_id'), 'adms_credentials', ['id'], unique=False)
    op.create_table('adms_registered_employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=True),
    sa.Column('employee_name', sa.String(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adms_registered_employees_employee_id'), 'adms_registered_employees', ['employee_id'], unique=True)
    op.create_index(op.f('ix_adms_registered_employees_id'), 'adms_registered_employees', ['id'], unique=False)
    op.create_table('adms_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_url', sa.String(), nullable=True),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('device_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('timezone_offset', sa.Integer(), nullable=True),
    sa.Column('last_contact', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adms_targets_id'), 'adms_targets', ['id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_value', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_ip', sa.String(length=45), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_id'), 'api_keys', ['id'], unique=False)
    op.create_index(op.f('ix_api_keys_key_value'), 'api_keys', ['key_value'], unique=True)
    op.create_table('app_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_configs_id'), 'app_configs', ['id'], unique=False)
    op.create_index(op.f('ix_app_configs_key'), 'app_configs', ['key'], unique=True)
    op.create_table('branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('radius_meters', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('qr_code_enabled', sa.Boolean(), nullable=False),
    sa.Column('qr_code_data', sa.String(length=256), nullable=True),
    sa.Column('nfc_enabled', sa.Boolean(), nullable=False),
    sa.Column('nfc_tag_data', sa.String(length=256), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branches_id'), 'branches', ['id'], unique=False)
    op.create_table('employee_supervisors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supervisor_id', sa.String(length=50), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_supervisor_mapping', 'employee_supervisors', ['supervisor_id', 'employee_id'], unique=True)
    op.create_index(op.f('ix_employee_supervisors_employee_id'), 'employee_supervisors', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_supervisors_id'), 'employee_supervisors', ['id'], unique=False)
    op.create_index(op.f('ix_employee_supervisors_supervisor_id'), 'employee_supervisors', ['supervisor_id'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adms_id', sa.String(), nullable=True),
    sa.Column('employee_id', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_synced', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_adms_id'), 'employees', ['adms_id'], unique=False)
    op.create_index(op.f('ix_employees_employee_id'), 'employees', ['employee_id'], unique=True)
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.create_table('punch_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=True),
    sa.Column('device_uuid', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('is_mock_location', sa.Boolean(), nullable=True),
    sa.Column('biometric_verified', sa.Boolean(), nullable=True),
    sa.Column('punch_type', sa.String(), nullable=True),
    sa.Column('tz_offset_minutes', sa.Integer(), nullable=True),
    sa.Column('adms_status', sa.String(), nullable=True),
    sa.Column('client_punch_id', sa.String(), nullable=True),
    sa.Column('gps_time_validated', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('selfie_filename', sa.String(length=500), nullable=True),
    sa.Column('server_sync_status', sa.String(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('sync_error', sa.String(length=500), nullable=True),
    sa.Column('sync_retry_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_punchlog_date', 'punch_logs', ['timestamp'], unique=False)
    op.create_index('idx_punchlog_employee_date', 'punch_logs', ['employee_id', 'timestamp'], unique=False)
    op.create_index('idx_punchlog_employee_type_date', 'punch_logs', ['employee_id', 'punch_type', 'timestamp'], unique=False)
    op.create_index('idx_punchlog_sync_status', 'punch_logs', ['adms_status'], unique=False)
    op.create_index(op.f('ix_punch_logs_client_punch_id'), 'punch_logs', ['client_punch_id'], unique=True)
    op.create_index(op.f('ix_punch_logs_employee_id'), 'punch_logs', ['employee_id'], unique=False)
    op.create_index(op.f('ix_punch_logs_id'), 'punch_logs', ['id'], unique=False)
    op.create_table('punch_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('adms_status_code', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('color_hex', sa.String(), nullable=True),
    sa.Column('requires_geofence', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_punch_types_code'), 'punch_types', ['code'], unique=True)
    op.create_index(op.f('ix_punch_types_id'), 'punch_types', ['id'], unique=False)
    op.create_table('attendance_corrections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('original_punch_id', sa.Integer(), nullable=True),
    sa.Column('correction_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('proposed_timestamp', sa.DateTime(), nullable=True),
    sa.Column('proposed_punch_type', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('reviewed_by', sa.String(length=50), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['original_punch_id'], ['punch_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_correction_employee', 'attendance_corrections', ['employee_id'], unique=False)
    op.create_index('idx_correction_status', 'attendance_corrections', ['status'], unique=False)
    op.create_index(op.f('ix_attendance_corrections_employee_id'), 'attendance_corrections', ['employee_id'], unique=False)
    op.create_index(op.f('ix_attendance_corrections_id'), 'attendance_corrections', ['id'], unique=False)
    op.create_table('branch_checkpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('radius_meters', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_checkpoint_branch', 'branch_checkpoints', ['branch_id'], unique=False)
    op.create_index(op.f('ix_branch_checkpoints_branch_id'), 'branch_checkpoints', ['branch_id'], unique=False)
    op.create_index(op.f('ix_branch_checkpoints_id'), 'branch_checkpoints', ['id'], unique=False)
    op.create_table('device_bindings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=True),
    sa.Column('device_uuid', sa.String(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('api_key_id', sa.Integer(), nullable=True),
    sa.Column('device_label', sa.String(), nullable=True),
    sa.Column('registration_status', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('fcm_token', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_device_binding_device', 'device_bindings', ['device_uuid'], unique=False)
    op.create_index('idx_device_binding_employee', 'device_bindings', ['employee_id'], unique=False)
    op.create_index(op.f('ix_device_bindings_device_uuid'), 'device_bindings', ['device_uuid'], unique=False)
    op.create_index(op.f('ix_device_bindings_employee_id'), 'device_bindings', ['employee_id'], unique=False)
    op.create_index(op.f('ix_device_bindings_id'), 'device_bindings', ['id'], unique=False)
    op.create_table('device_branch_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('binding_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['binding_id'], ['device_bindings.id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('binding_id', 'branch_id')
    )
    op.create_index(op.f('ix_device_branch_assignments_binding_id'), 'device_branch_assignments', ['binding_id'], unique=False)
    op.create_index(op.f('ix_device_branch_assignments_id'), 'device_branch_assignments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_branch_assignments_id'), table_name='device_branch_assignments')
    op.drop_index(op.f('ix_device_branch_assignments_binding_id'), table_name='device_branch_assignments')
    op.drop_table('device_branch_assignments')
    op.drop_index(op.f('ix_device_bindings_id'), table_name='device_bindings')
    op.drop_index(op.f('ix_device_bindings_employee_id'), table_name='device_bindings')
    op.drop_index(op.f('ix_device_bindings_device_uuid'), table_name='device_bindings')
    op.drop_index('idx_device_binding_employee', table_name='device_bindings')
    op.drop_index('idx_device_binding_device', table_name='device_bindings')
    op.drop_table('device_bindings')
    op.drop_index(op.f('ix_branch_checkpoints_id'), table_name='branch_checkpoints')
    op.drop_index(op.f('ix_branch_checkpoints_branch_id'), table_name='branch_checkpoints')
    op.drop_index('idx_checkpoint_branch', table_name='branch_checkpoints')
    op.drop_table('branch_checkpoints')
    op.drop_index(op.f('ix_attendance_corrections_id'), table_name='attendance_corrections')
    op.drop_index(op.f('ix_attendance_corrections_employee_id'), table_name='attendance_corrections')
    op.drop_index('idx_correction_status', table_name='attendance_corrections')
    op.drop_index('idx_correction_employee', table_name='attendance_corrections')
    op.drop_table('attendance_corrections')
    op.drop_index(op.f('ix_punch_types_id'), table_name='punch_types')
    op.drop_index(op.f('ix_punch_types_code'), table_name='punch_types')
    op.drop_table('punch_types')
    op.drop_index(op.f('ix_punch_logs_id'), table_name='punch_logs')
    op.drop_index(op.f('ix_punch_logs_employee_id'), table_name='punch_logs')
    op.drop_index(op.f('ix_punch_logs_client_punch_id'), table_name='punch_logs')
    op.drop_index('idx_punchlog_sync_status', table_name='punch_logs')
    op.drop_index('idx_punchlog_employee_type_date', table_name='punch_logs')
    op.drop_index('idx_punchlog_employee_date', table_name='punch_logs')
    op.drop_index('idx_punchlog_date', table_name='punch_logs')
    op.drop_table('punch_logs')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_employee_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_adms_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_employee_supervisors_supervisor_id'), table_name='employee_supervisors')
    op.drop_index(op.f('ix_employee_supervisors_id'), table_name='employee_supervisors')
    op.drop_index(op.f('ix_employee_supervisors_employee_id'), table_name='employee_supervisors')
    op.drop_index('idx_supervisor_mapping', table_name='employee_supervisors')
    op.drop_table('employee_supervisors')
    op.drop_index(op.f('ix_branches_id'), table_name='branches')
    op.drop_table('branches')
    op.drop_index(op.f('ix_app_configs_key'), table_name='app_configs')
    op.drop_index(op.f('ix_app_configs_id'), table_name='app_configs')
    op.drop_table('app_configs')
    op.drop_index(op.f('ix_api_keys_key_value'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_id'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_adms_targets_id'), table_name='adms_targets')
    op.drop_table('adms_targets')
    op.drop_index(op.f('ix_adms_registered_employees_id'), table_name='adms_registered_employees')
    op.drop_index(op.f('ix_adms_registered_employees_employee_id'), table_name='adms_registered_employees')
    op.drop_table('adms_registered_employees')
    op.drop_index(op.f('ix_adms_credentials_id'), table_name='adms_credentials')
    op.drop_table('adms_credentials')
    op.drop_index(op.f('ix_admin_users_username'), table_name='admin_users')
    op.drop_index(op.f('ix_admin_users_id'), table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
