"""Add system error logs table

Revision ID: 79db5f5796e0
Revises: 9d6887d52a33
Create Date: 2026-05-25 13:03:25.661061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79db5f5796e0'
down_revision: Union[str, Sequence[str], None] = '9d6887d52a33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_error_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(length=500), nullable=False),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('component', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_error_logs_id'), 'system_error_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_error_logs_id'), table_name='system_error_logs')
    op.drop_table('system_error_logs')
    # ### end Alembic commands ###
