"""add_shifts_companies_leaves_and_audit_logs

Revision ID: 9d6887d52a33
Revises: 4c757a619595
Create Date: 2026-05-25 11:28:21.414927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d6887d52a33'
down_revision: Union[str, Sequence[str], None] = '4c757a619595'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adms_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adms_credentials_id'), 'adms_credentials', ['id'], unique=False)
    op.create_table('app_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_configs_id'), 'app_configs', ['id'], unique=False)
    op.create_index(op.f('ix_app_configs_key'), 'app_configs', ['key'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_username', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=150), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.String(length=50), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_admin_username'), 'audit_logs', ['admin_username'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('employee_supervisors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supervisor_id', sa.String(length=50), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_supervisor_mapping', 'employee_supervisors', ['supervisor_id', 'employee_id'], unique=True)
    op.create_index(op.f('ix_employee_supervisors_employee_id'), 'employee_supervisors', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_supervisors_id'), 'employee_supervisors', ['id'], unique=False)
    op.create_index(op.f('ix_employee_supervisors_supervisor_id'), 'employee_supervisors', ['supervisor_id'], unique=False)
    op.create_table('holidays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_holidays_date'), 'holidays', ['date'], unique=True)
    op.create_index(op.f('ix_holidays_id'), 'holidays', ['id'], unique=False)
    op.create_table('punch_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('adms_status_code', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('color_hex', sa.String(), nullable=True),
    sa.Column('requires_geofence', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_punch_types_code'), 'punch_types', ['code'], unique=True)
    op.create_index(op.f('ix_punch_types_id'), 'punch_types', ['id'], unique=False)
    op.create_table('shift_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.String(length=5), nullable=True),
    sa.Column('end_time', sa.String(length=5), nullable=True),
    sa.Column('grace_minutes', sa.Integer(), nullable=True),
    sa.Column('min_work_hours', sa.Float(), nullable=True),
    sa.Column('overtime_after_hours', sa.Float(), nullable=True),
    sa.Column('working_days', sa.String(length=50), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('schedule_type', sa.String(length=50), nullable=True),
    sa.Column('interval_days', sa.Integer(), nullable=True),
    sa.Column('anchor_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shift_schedules_id'), 'shift_schedules', ['id'], unique=False)
    op.create_table('attendance_corrections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('original_punch_id', sa.Integer(), nullable=True),
    sa.Column('correction_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('proposed_timestamp', sa.DateTime(), nullable=True),
    sa.Column('proposed_punch_type', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('reviewed_by', sa.String(length=50), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['original_punch_id'], ['punch_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_correction_employee', 'attendance_corrections', ['employee_id'], unique=False)
    op.create_index('idx_correction_status', 'attendance_corrections', ['status'], unique=False)
    op.create_index(op.f('ix_attendance_corrections_employee_id'), 'attendance_corrections', ['employee_id'], unique=False)
    op.create_index(op.f('ix_attendance_corrections_id'), 'attendance_corrections', ['id'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('shift_schedule_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shift_schedule_id'], ['shift_schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_code'), 'companies', ['code'], unique=True)
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_table('branch_checkpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('radius_meters', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('geofence_type', sa.String(length=20), nullable=False),
    sa.Column('polygon_coordinates', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_checkpoint_branch', 'branch_checkpoints', ['branch_id'], unique=False)
    op.create_index(op.f('ix_branch_checkpoints_branch_id'), 'branch_checkpoints', ['branch_id'], unique=False)
    op.create_index(op.f('ix_branch_checkpoints_id'), 'branch_checkpoints', ['id'], unique=False)
    op.create_table('device_branch_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('binding_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['binding_id'], ['device_bindings.id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('binding_id', 'branch_id')
    )
    op.create_index(op.f('ix_device_branch_assignments_binding_id'), 'device_branch_assignments', ['binding_id'], unique=False)
    op.create_index(op.f('ix_device_branch_assignments_id'), 'device_branch_assignments', ['id'], unique=False)
    op.create_table('employee_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('shift_schedule_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['shift_schedule_id'], ['shift_schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_groups_branch_id'), 'employee_groups', ['branch_id'], unique=False)
    op.create_index(op.f('ix_employee_groups_id'), 'employee_groups', ['id'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adms_id', sa.String(), nullable=True),
    sa.Column('employee_id', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('employee_type', sa.String(length=50), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('shift_schedule_id', sa.Integer(), nullable=True),
    sa.Column('last_synced', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['employee_groups.id'], ),
    sa.ForeignKeyConstraint(['shift_schedule_id'], ['shift_schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_adms_id'), 'employees', ['adms_id'], unique=False)
    op.create_index(op.f('ix_employees_employee_id'), 'employees', ['employee_id'], unique=True)
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.create_table('leave_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('leave_type', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('approved_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_requests_employee_id'), 'leave_requests', ['employee_id'], unique=False)
    op.create_index(op.f('ix_leave_requests_id'), 'leave_requests', ['id'], unique=False)
    op.add_column('admin_users', sa.Column('role', sa.String(), nullable=True))
    op.add_column('adms_targets', sa.Column('timezone_offset', sa.Integer(), nullable=True))
    op.add_column('api_keys', sa.Column('last_used_ip', sa.String(length=45), nullable=True))
    op.add_column('api_keys', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.add_column('branches', sa.Column('geofence_type', sa.String(length=20), nullable=False))
    op.add_column('branches', sa.Column('polygon_coordinates', sa.Text(), nullable=True))
    op.add_column('branches', sa.Column('qr_code_enabled', sa.Boolean(), nullable=False))
    op.add_column('branches', sa.Column('qr_code_data', sa.String(length=256), nullable=True))
    op.add_column('branches', sa.Column('nfc_enabled', sa.Boolean(), nullable=False))
    op.add_column('branches', sa.Column('nfc_tag_data', sa.String(length=256), nullable=True))
    op.add_column('branches', sa.Column('company_id', sa.Integer(), nullable=True))
    op.add_column('branches', sa.Column('shift_schedule_id', sa.Integer(), nullable=True))
    op.add_column('branches', sa.Column('timezone_offset', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_geofence_zones_id'), table_name='branches')
    op.create_index(op.f('ix_branches_id'), 'branches', ['id'], unique=False)
    op.create_foreign_key(None, 'branches', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(None, 'branches', 'shift_schedules', ['shift_schedule_id'], ['id'])
    op.add_column('device_bindings', sa.Column('api_key_id', sa.Integer(), nullable=True))
    op.add_column('device_bindings', sa.Column('device_label', sa.String(), nullable=True))
    op.add_column('device_bindings', sa.Column('registration_status', sa.String(), nullable=True))
    op.add_column('device_bindings', sa.Column('approved_at', sa.DateTime(), nullable=True))
    op.add_column('device_bindings', sa.Column('approved_by', sa.String(), nullable=True))
    op.add_column('device_bindings', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('device_bindings', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('device_bindings', sa.Column('fcm_token', sa.String(length=500), nullable=True))
    op.drop_index(op.f('ix_device_bindings_employee_id'), table_name='device_bindings')
    op.create_index(op.f('ix_device_bindings_employee_id'), 'device_bindings', ['employee_id'], unique=False)
    op.create_index('idx_device_binding_device', 'device_bindings', ['device_uuid'], unique=False)
    op.create_index('idx_device_binding_employee', 'device_bindings', ['employee_id'], unique=False)
    op.create_foreign_key(None, 'device_bindings', 'api_keys', ['api_key_id'], ['id'])
    op.add_column('punch_logs', sa.Column('tz_offset_minutes', sa.Integer(), nullable=True))
    op.add_column('punch_logs', sa.Column('client_punch_id', sa.String(), nullable=True))
    op.add_column('punch_logs', sa.Column('gps_time_validated', sa.Boolean(), nullable=True))
    op.add_column('punch_logs', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('punch_logs', sa.Column('selfie_filename', sa.String(length=500), nullable=True))
    op.add_column('punch_logs', sa.Column('server_sync_status', sa.String(), nullable=True))
    op.add_column('punch_logs', sa.Column('synced_at', sa.DateTime(), nullable=True))
    op.add_column('punch_logs', sa.Column('sync_error', sa.String(length=500), nullable=True))
    op.add_column('punch_logs', sa.Column('sync_retry_count', sa.Integer(), nullable=True))
    op.create_index('idx_punchlog_date', 'punch_logs', ['timestamp'], unique=False)
    op.create_index('idx_punchlog_employee_date', 'punch_logs', ['employee_id', 'timestamp'], unique=False)
    op.create_index('idx_punchlog_employee_type_date', 'punch_logs', ['employee_id', 'punch_type', 'timestamp'], unique=False)
    op.create_index('idx_punchlog_sync_status', 'punch_logs', ['adms_status'], unique=False)
    op.create_index(op.f('ix_punch_logs_client_punch_id'), 'punch_logs', ['client_punch_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_punch_logs_client_punch_id'), table_name='punch_logs')
    op.drop_index('idx_punchlog_sync_status', table_name='punch_logs')
    op.drop_index('idx_punchlog_employee_type_date', table_name='punch_logs')
    op.drop_index('idx_punchlog_employee_date', table_name='punch_logs')
    op.drop_index('idx_punchlog_date', table_name='punch_logs')
    op.drop_column('punch_logs', 'sync_retry_count')
    op.drop_column('punch_logs', 'sync_error')
    op.drop_column('punch_logs', 'synced_at')
    op.drop_column('punch_logs', 'server_sync_status')
    op.drop_column('punch_logs', 'selfie_filename')
    op.drop_column('punch_logs', 'notes')
    op.drop_column('punch_logs', 'gps_time_validated')
    op.drop_column('punch_logs', 'client_punch_id')
    op.drop_column('punch_logs', 'tz_offset_minutes')
    op.drop_constraint(None, 'device_bindings', type_='foreignkey')
    op.drop_index('idx_device_binding_employee', table_name='device_bindings')
    op.drop_index('idx_device_binding_device', table_name='device_bindings')
    op.drop_index(op.f('ix_device_bindings_employee_id'), table_name='device_bindings')
    op.create_index(op.f('ix_device_bindings_employee_id'), 'device_bindings', ['employee_id'], unique=1)
    op.drop_column('device_bindings', 'fcm_token')
    op.drop_column('device_bindings', 'is_active')
    op.drop_column('device_bindings', 'notes')
    op.drop_column('device_bindings', 'approved_by')
    op.drop_column('device_bindings', 'approved_at')
    op.drop_column('device_bindings', 'registration_status')
    op.drop_column('device_bindings', 'device_label')
    op.drop_column('device_bindings', 'api_key_id')
    op.drop_constraint(None, 'branches', type_='foreignkey')
    op.drop_constraint(None, 'branches', type_='foreignkey')
    op.drop_index(op.f('ix_branches_id'), table_name='branches')
    op.create_index(op.f('ix_geofence_zones_id'), 'branches', ['id'], unique=False)
    op.drop_column('branches', 'timezone_offset')
    op.drop_column('branches', 'shift_schedule_id')
    op.drop_column('branches', 'company_id')
    op.drop_column('branches', 'nfc_tag_data')
    op.drop_column('branches', 'nfc_enabled')
    op.drop_column('branches', 'qr_code_data')
    op.drop_column('branches', 'qr_code_enabled')
    op.drop_column('branches', 'polygon_coordinates')
    op.drop_column('branches', 'geofence_type')
    op.drop_column('api_keys', 'expires_at')
    op.drop_column('api_keys', 'last_used_ip')
    op.drop_column('adms_targets', 'timezone_offset')
    op.drop_column('admin_users', 'role')
    op.drop_index(op.f('ix_leave_requests_id'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_employee_id'), table_name='leave_requests')
    op.drop_table('leave_requests')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_employee_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_adms_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_employee_groups_id'), table_name='employee_groups')
    op.drop_index(op.f('ix_employee_groups_branch_id'), table_name='employee_groups')
    op.drop_table('employee_groups')
    op.drop_index(op.f('ix_device_branch_assignments_id'), table_name='device_branch_assignments')
    op.drop_index(op.f('ix_device_branch_assignments_binding_id'), table_name='device_branch_assignments')
    op.drop_table('device_branch_assignments')
    op.drop_index(op.f('ix_branch_checkpoints_id'), table_name='branch_checkpoints')
    op.drop_index(op.f('ix_branch_checkpoints_branch_id'), table_name='branch_checkpoints')
    op.drop_index('idx_checkpoint_branch', table_name='branch_checkpoints')
    op.drop_table('branch_checkpoints')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_code'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_attendance_corrections_id'), table_name='attendance_corrections')
    op.drop_index(op.f('ix_attendance_corrections_employee_id'), table_name='attendance_corrections')
    op.drop_index('idx_correction_status', table_name='attendance_corrections')
    op.drop_index('idx_correction_employee', table_name='attendance_corrections')
    op.drop_table('attendance_corrections')
    op.drop_index(op.f('ix_shift_schedules_id'), table_name='shift_schedules')
    op.drop_table('shift_schedules')
    op.drop_index(op.f('ix_punch_types_id'), table_name='punch_types')
    op.drop_index(op.f('ix_punch_types_code'), table_name='punch_types')
    op.drop_table('punch_types')
    op.drop_index(op.f('ix_holidays_id'), table_name='holidays')
    op.drop_index(op.f('ix_holidays_date'), table_name='holidays')
    op.drop_table('holidays')
    op.drop_index(op.f('ix_employee_supervisors_supervisor_id'), table_name='employee_supervisors')
    op.drop_index(op.f('ix_employee_supervisors_id'), table_name='employee_supervisors')
    op.drop_index(op.f('ix_employee_supervisors_employee_id'), table_name='employee_supervisors')
    op.drop_index('idx_supervisor_mapping', table_name='employee_supervisors')
    op.drop_table('employee_supervisors')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_admin_username'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_app_configs_key'), table_name='app_configs')
    op.drop_index(op.f('ix_app_configs_id'), table_name='app_configs')
    op.drop_table('app_configs')
    op.drop_index(op.f('ix_adms_credentials_id'), table_name='adms_credentials')
    op.drop_table('adms_credentials')
    # ### end Alembic commands ###
